steps:
  - id: build-backend
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_IMAGE}
      - .
    dir: backend

  - id: push-backend
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_IMAGE}

  - id: deploy-backend
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image
      - ${_IMAGE}
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --port
      - '8080'

images:
  - ${_IMAGE}

substitutions:
  _REGION: asia-south1
  _SERVICE: india-report-backend
  _IMAGE: asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/india-report-backend:$SHORT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
